---
- hosts: standalone
  become: true
  become_user: root
  gather_facts: true
  vars_files: vars/defaults.yaml

  tasks:

  - name: Prepare host on RHEL system
    when:
      - ansible_facts.distribution == 'RedHat'
    block:
      - name: install rhos-release
        yum:
          state: installed
          name:
          - http://download.devel.redhat.com/rcm-guest/puddles/OpenStack/rhos-release/rhos-release-latest.noarch.rpm
          disable_gpg_check: True

      - name: Configure rhos release "{{ rhos_release }}"
        shell: rhos-release "{{ rhos_release }}"

      - name: Fetch the Red Hat root certificate
        get_url:
          dest: /etc/pki/ca-trust/source/anchors/RH-IT-Root-CA.crt
          url: https://password.corp.redhat.com/RH-IT-Root-CA.crt

      - name: Add the certificate to the local trust bundle
        shell: |
          update-ca-trust enable
          update-ca-trust extract

  - name: Prepare host on CentOS system
    when:
      - ansible_facts.distribution == 'CentOS'
    block:
      - name: configure tripleo repositories
        import_role:
          name: tripleo.operator.tripleo_repos

  - name: Upgrade all packages
    yum:
      name: '*'
      state: latest
    register: yum

  - name: Reboot if we updated packages
    reboot:
    when: yum.changed

  - name: Set FQDN
    set_fact:
      fqdn: "{{ hostname }}.{{ clouddomain }}"

  - name: Set hostname to "{{ fqdn }}"
    hostname:
      name: "{{ fqdn }}"

  - name: Allow 'wheel' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: Create the stack user
    user:
      name: stack
      groups: wheel
